CREATE TABLE IF NOT EXISTS measurements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sensor VARCHAR(64) NOT NULL,
    value DOUBLE NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_sensor_ts (sensor, ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
